name: Build Aseprite with Skia

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      shell: bash
      run: |
        choco install ninja git cmake 7zip -y

    - name: Fetch Skia (official way)
      shell: bash
      run: |
        git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
        echo "$GITHUB_WORKSPACE/depot_tools" >> $GITHUB_PATH
        export PATH="$GITHUB_WORKSPACE/depot_tools:$PATH"
        
        mkdir $GITHUB_WORKSPACE/skia
        cd $GITHUB_WORKSPACE/skia
        fetch skia
        cd skia
        bin/gn gen out/Release-x64 --args='is_official_build=true is_component_build=false target_cpu="x64"'
        ninja -C out/Release-x64

    - name: Configure CMake
      shell: bash
      run: |
        cmake -S . -B build -G Ninja ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DLAF_BACKEND=skia ^
          -DSKIA_DIR=$GITHUB_WORKSPACE/skia/skia ^
          -DSKIA_LIBRARY_DIR=$GITHUB_WORKSPACE/skia/skia/out/Release-x64 ^
          -DSKIA_LIBRARY=$GITHUB_WORKSPACE/skia/skia/out/Release-x64/skia.lib

    - name: Build Aseprite
      shell: bash
      run: |
        cmake --build build --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-exe
        path: build/bin/aseprite.exe
